### ISSUE TITLE
ingest error 

### ISSUE THREAD

**Issue by jorge80** [Sotera/newman#47]
vagrant@vagrant-ubuntu-trusty-32:/srv/software/newman/work_dir$ cat ingest_20150611003032.err.log
Traceback (most recent call last):
  File "./ingest/mitie/mitie_entity_ingest_file.py", line 65, in <module>
    r = extract(email_id, body)
  File "./ingest/mitie/mitie_entity_ingest_file.py", line 29, in extract_entities
    for rng, tag in entities ]
ValueError: too many values to unpack
---

**Comment by cchabalk** [comment]
The ingest process has changed significantly.  Suggested closed by S. Mahoney.
